### ISSUE TITLE
min_jerk_traj is not in the install list in CMakeLists

### ISSUE THREAD

**Issue by ZzhengP** [syroco/orca_ros#1]
As seen in the title, the min_jerk_traj is not in the list of install in CMakeLists.  So can't find node min_jerk_traj when launching min_jerk_traj launch file. Fixed it by adding min_jerk_traj in the install list in CMakeLists.

**Comment by rlober** [comment]
Thanks for the heads up! 

Fixed in cee914b7403fad0643b8021276a48efabf32cf79
